# Generated by Django 5.2.4 on 2025-07-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('core_values', models.TextField()),
                ('goals', models.TextField()),
                ('history_summary', models.TextField()),
                ('formation_summary', models.TextField()),
            ],
        ),
    ]
