# Generated by Django 5.2.4 on 2025-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='official',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
