# Generated by Django 5.2.4 on 2025-08-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_official_designation_alter_official_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_content', models.TextField()),
                ('change_designation', models.TextField()),
                ('salary_scale', models.TextField()),
                ('training_institutions', models.TextField()),
            ],
        ),
    ]
