# Generated by Django 5.2.5 on 2025-09-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_formation_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpdarticle',
            name='cpd_hours',
        ),
        migrations.RemoveField(
            model_name='cpdarticle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cpdarticle',
            name='image_url',
        ),
    ]
