# Generated by Django 5.2.5 on 2025-09-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_news_cpdarticle_content_alter_cpdarticle_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
