# Generated by Django 5.2.5 on 2025-09-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_managers_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership_type',
            field=models.CharField(choices=[('full', 'FULL MEMBERSHIP'), ('associate', 'ASSOCIATE MEMBERSHIP'), ('student', 'STUDENT MEMBERSHIP'), ('fellow', 'COLLEGE OF FELLOWS')], default='full', max_length=50),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('magazine', 'Magazine'), ('article', 'Article'), ('event', 'Event')], max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('paystack_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='inactive', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('full', 'FULL MEMBERSHIP'), ('associate', 'ASSOCIATE MEMBERSHIP'), ('student', 'STUDENT MEMBERSHIP'), ('fellow', 'COLLEGE OF FELLOWS')], default='full', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
