# Generated by Django 5.2.5 on 2025-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_event_job_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
