# Generated by Django 5.2.5 on 2025-09-15 16:21

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cover_image',
            field=models.ImageField(default='static/images/placeholder.jpg', upload_to='publication_covers/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(upload_to='publications/', validators=[members.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
