# Generated by Django 5.2.5 on 2025-09-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_publication_cover_image_alter_publication_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
    ]
