# Generated by Django 5.2.5 on 2025-09-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
